name: Manual Selective Publish

on:
  workflow_dispatch:
    inputs:
      package:
        description: "배포할 패키지"
        required: true
        type: choice
        options:
          - eslint
          - prettier
          - tsconfig

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Extract package directory
        id: extract
        run: |
          echo "PACKAGE_SCOPE=${{ github.event.inputs.package }}"
          PACKAGE_NAME=$(basename "${{ github.event.inputs.package }}")
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_OUTPUT
          echo "Directory: packages/$PACKAGE_NAME"

      - name: Publish selected package
        run: |
          cd packages/${{ steps.extract.outputs.PACKAGE_NAME }}
          pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
