name: 패키지 배포

on:
  workflow_dispatch:
    inputs:
      package:
        description: "배포할 패키지"
        required: true
        type: choice
        options:
          - eslint
          - prettier
          - tsconfig

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Publish selected package
        run: |
          cd packages/${{ github.event.inputs.package }}
          pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
